---
title: "proofs_rober"
author: "Papoula Petri-Romão & Roberto Mediavilla"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Data preparation

I run the heroes_dataset_wp2_v2.Rmd file until chunk #57 (before recoding NAs)

```{r}
df <- df_str_red
```

I copy the code to obtain variable classes and labels

```{r}
# Variable class

df <- 
  df %>% 
  mutate(
    across(
      .cols = c(MP22,
                SD07,
                SD08a,
                TR16,
                TR17),
      .fns = ~ str_extract(., ".[:digit:]*") %>% as.numeric
    ),
    across(
      .cols = c(starts_with(c("AD",
                              "GAD",
                              "PCPTSD",
                              "PHQ")),
                RE57:RE63),
      .fns = as.numeric),
    across(
      .cols = CountryName:quartile_3,
      .fns = as.numeric
    )
    ) %>% 
  mutate(
    across(
      .cols = where(is.character) & !Identificador,
      .fns = as.factor
    )
  )

# Variable labels

## Step 1. Get colnames

raw_t0 %>% 
  select(ends_with(colnames(df_str_red))) %>% 
  colnames() -> t0_uniq

raw_t1 %>% 
  select(matches(colnames(df_str_red))) %>% 
  select(!matches(t0_uniq)) %>% 
  colnames() -> t1_uniq

raw_t2 %>% 
  select(matches(colnames(df_str_red))) %>% 
  select(!matches(t0_uniq)) %>% 
  select(!matches(t1_uniq)) %>% 
  rename_with(.,
              ~ str_replace(.,
                    "[:alnum:]+3_",
                    "")) %>% 
  colnames() -> t2_uniq

df %>% 
  select(!matches(t0_uniq)) %>% 
  select(!matches(t1_uniq)) %>% 
  select(!matches(t2_uniq)) %>% 
  colnames() -> new

# Tengo 130 variables (en df_str_red hay 206)

labs_t0 <- 
  codebook_t0 %>% 
  select(short_name, item) %>% 
  filter(short_name %in% t0_uniq) %>% 
  with(.,
       split(item,
             factor(short_name, levels = unique(short_name))))

labs_t1 <- 
  codebook_t1 %>% 
  select(short_name, item) %>% 
  filter(short_name %in% t1_uniq) %>% 
  with(.,
       split(item,
             factor(short_name, levels = unique(short_name))))

labs_t2 <- 
  codebook_t2 %>% 
  select(short_name, item) %>% 
  filter(short_name %in% t2_uniq) %>% 
  with(.,
       split(item,
             factor(short_name, levels = unique(short_name))))

labs_new <- 
  new %>% 
  as_tibble() %>% 
  mutate(short_name = value,
         item = "unknown") %>% 
  select(!value) %>% 
  with(.,
     split(item,
           factor(short_name, levels = unique(short_name))))

labs <- c(labs_t0, labs_t1, labs_t2, labs_new)

labelled::var_label(df) <- labs

# Hashed id

library(openssl)

df <- 
  df %>% 
  mutate(hashed_id = md5(Identificador))

df <- 
  df %>% 
  select(!Identificador) %>% 
  relocate(hashed_id)

# Clean names

df <- 
  df %>% 
  janitor::clean_names(.)
```

I will now focus on the first wave and include only the variables I'm interested in

```{r}
df1 <- 
  df %>% 
  filter(wave == 1,
           !is.na(assessment_week)) %>%  # This removes "fake" missing data
  select(hashed_id,
         tr15,
         tr16,
         tr17,
         mp25a,
         mp25b:mp25e,
         ep32,
         mp18,
         mp21,
         mp23,
         mp22,
         mp25,
         mp24,
         starts_with(c("phq", "ad"))) 
```

At this stage, I only recode NAs, so that we can look at the actual distribution of stressors

```{r}
df1 <- 
  df1 %>% 
  mutate(
    mp25a = fct_recode(mp25a,
                       NULL = "2"),
    mp25b = fct_recode(mp25b,
                       NULL = "2",
                       NULL = "3"),
    mp25d = fct_recode(mp25d,
                       NULL = "4"), # Option 4 added in waves 2 and 3
    ep32 = fct_recode(ep32,
                      NULL = "2",
                      NULL = "3"),
    mp24 = as.numeric(mp24),
    mp18 = fct_recode(mp18,
                      NULL = "2"),
    
    )

df1 <- 
  df1 %>% 
  mutate(
    ghq_total = select(., c(ad34:ad45)) %>% rowSums(),
    phq_total = select(., c(phq68:phq76)) %>% rowSums()
  )
```

# Correlation matrix

```{r}
df1 %>% 
  mutate(
    across(
      where(is.factor),
      as.character
    ),
    across(
      where(is.character),
      as.numeric
    )
  ) %>% 
  select(!c(hashed_id,
            phq68:ad45)
  ) %>% 
  psych::cor.plot(.)
```

Linear models

```{r}
# GHQ12

df1 %>% 
  select(!c(hashed_id,
            phq68:ad45)) %>% 
  mutate(
    across(
      c(tr16, tr17, mp25c, mp25d, mp25e, mp21, mp23, mp22),
      as.character
    ),
    across(
      where(is.character),
      as.numeric
    )
  ) %>% 
  map(~ lm(ghq_total ~ .x, df1) %>% summary())

# PHQ-9

df1 %>% 
  select(!c(hashed_id,
            phq68:ad45)) %>% 
  mutate(
    across(
      c(tr16, tr17, mp25c, mp25d, mp25e, mp21, mp23, mp22),
      as.character
    ),
    across(
      where(is.character),
      as.numeric
    )
  ) %>% 
  map(~ lm(ghq_total ~ .x, df1) %>% summary())
```




